version: '3'

services:
  server:
    build: 
      context: ./app_server
      dockerfile: Dockerfile1
    image: ubuntu
    ports:
      - "5000:5000"
    volumes:
      - .:/app_server

  sender:
    build:
      context: ./app_server
      dockerfile: Dockerfile2
    image: ubuntu
    ports:
      - "5000:5000"
    volumes:
      - .:/app_server
    links:
      - server

