version: '3'

services:
  server:
    build: 
      context: ./recieve
      dockerfile: Dockerfile1
    image: servidor
    volumes: 
      - ./recieve:/Server
    ports:
      - "5000:5000"

  send:
    build:
      context: ./send
      dockerfile: Dockerfile2
    image: sender
    volumes: 
      - ./send:/Cliente
    depends_on:
      - server
