version: '3'

services:
  server:
    build: 
      context: ./recieve
      dockerfile: Dockerfile1
    image: ubuntu
    command: python3 /usr/bin/recieve.py
    ports:
      - "5000:5000"

  send:
    build:
      context: ./send
      dockerfile: Dockerfile2
    image: ubuntu
    command: python3 /usr/bin/send.py
    depends_on:
      - server
