version: '3'

services:
  headnode:
    build: 
      context: ./Headnode
      dockerfile: Dockerfile1
    image: ubuntu
    command: python3 /usr/bin/headnode.py
    ports:
      - "5000-5004:5000-5004"

  cliente:
    build:
      context: ./Cliente
      dockerfile: Dockerfile2
    image: ubuntu
    command: python3 /usr/bin/cliente.py
    depends_on:
      - headnode
  datanode_1:
    build:
      context: ./Datanode_1
      dockerfile: Dockerfile3
    image: ubuntu
    command: python3 /usr/bin/datanode.py
    depends_on:
      - headnode
  datanode_2:
    build:
      context: ./Datanode_2
      dockerfile: Dockerfile3
    image: ubuntu
    command: python3 /usr/bin/datanode.py
    depends_on:
      - headnode
  datanode_3:
    build:
      context: ./Datanode_3
      dockerfile: Dockerfile3
    image: ubuntu
    command: python3 /usr/bin/datanode.py
    depends_on:
      - headnode

