version: '3'

services:
  headnode:
    build: 
      context: ./Headnode
      dockerfile: Dockerfile1
    image: ubuntu
    command: python3 /usr/bin/recieve.py
    ports:
      - "5000:5000"

  cliente:
    build:
      context: ./Cliente
      dockerfile: Dockerfile2
    image: ubuntu
    command: python3 /usr/bin/send.py
    depends_on:
      - headnode
  datanode_1:
    build:
      context: ./datanode_1
      dockerfile: Dockerfile3
    image: ubuntu
    command: python3 /usr/bin/XXX.py
    depends_on:
      - headnode
  datanode_2:
    build:
      context: ./datanode_2
      dockerfile: Dockerfile3
    image: ubuntu
    command: python3 /usr/bin/XXX.py
    depends_on:
      - headnode
  datanode_3:
    build:
      context: ./datanode_3
      dockerfile: Dockerfile3
    image: ubuntu
    command: python3 /usr/bin/XXX.py
    depends_on:
      - headnode
